spring.application.name=demo-rest

spring.graphql.graphiql.enabled=true

spring.graphql.path=/graphql

spring.graphql.schema.locations=classpath*:graphql/

dgs.graphql.schema-locations=classpath*:graphql/**/*.graphqls

spring.graphql.schema.introspection.enabled=true